### ISSUE TITLE
Don't build libs twice in the STATIC_ONLY case

### ISSUE THREAD

**Issue by winterz** [libical/libical#174]
When building static libraries only (cmake -DSTATIC_ONLY), the libraries are built twice.  stop doing that.

**Comment by krop** [comment]
Hey,

Can you give more information if this is still relevant ? I'm only seeing a random parallel build issue

**Comment by krop** [comment]
Never mind, reproduced.

**Comment by krop** [comment]
So.. this is the expected behaviour.
eg: in src/libical/CMakeLists.txt:

add_library(ical ${LIBRARY_TYPE} ${ical_LIB_SRCS})
add_dependencies(ical ical-header)
if(NOT SHARED_ONLY)
  add_library(ical-static STATIC ${ical_LIB_SRCS})
[...]

You're creating two libs when SHARED_ONLY is false. After that you're installing both but rename the library if the compiler isn't MSVC.

The question is: why do you need two libraries with different names when using MSVC ?

**Comment by winterz** [comment]
heck if I remember why things are like that.  However, I know I spent some time on it and never was able to come up with a satisfactory solution on Windows.  I'm not sure how to respond really.  

Perhaps a re-factorization of the CMake code using functions or macros would shed some light?  up to you, I don't feel much like playing with it myself.

**Comment by tonytheodore** [comment]
> The question is: why do you need two libraries with different names when using MSVC ?

With MSVC, a *.lib file can be either a static library containing object files (corresponds to *.a with gcc) or an "import library" containing references to the *.dll functions (*.dll.a with gcc/mingw). If building both shared and static libs, the static *.lib files are typically renamed to avoid clobbering.
