### ISSUE TITLE
Python Bindings

### ISSUE THREAD

**Issue by winterz** [libical/libical#201]
Bring back the Python bindings (see the src/python folder)

**Comment by GMLudo** [comment]
I've checked a little bit and I've tried to compile, it seems to have a lot of work :-/

The source code seems to be very old. Maybe, a restart from scratch should be a more useful approach.

Since the time this binding has been written, several approaches exist now to build Python bindings for C library, like ctypes, cython or CFFI.

To my knowledge, CFFI seems to become the standard in Python community, because it permits also alternative Python implementations le PyPy to use the C binding.

But I haven't not enough development experience with ctypes, cython and CFFI to know what's the easiest/best for libical.

**Comment by winterz** [comment]
yes, it is ancient.  I also have no idea how to proceed.
whatever you feel is best is ok with me.

**Comment by GMLudo** [comment]
Thank you for the free rein, however, I already found another alternative to do what I need :-/

**Comment by tintou** [comment]
Please note that it is possible to use libical-glib via the GObject introspection

**Comment by winterz** [comment]
yes, given the work needed to bring src/python back to life (which includes porting to python3), I think we remove src/python and point people to the libical-glib via the GObject introspection python which works very well and is maintained.

Any objections?

**Comment by winterz** [comment]
no objections.
closing this.
