### ISSUE TITLE
Test Harness:  run parser on various calendar files

### ISSUE THREAD

**Issue by winterz** [libical/libical#255]
Currently we build the test program 'parser', but we don't run it on any ics files to test anything.

So let's run 'parser' on a bunch/all of ics files under test-data. 

ie.
```
foreach file in `ls test-data/*.ics`
  parser $file

```

**Comment by ksuther** [comment]
I've added a cmake test so that parser runs on all the ics files in `test-data` at https://github.com/ksuther/libical/tree/parser-test, but since parser always returns an exit status of 0 it doesn't really do much useful (unless it crashes).

Did you have a particular failure or error in mind, other than crashing?

**Comment by winterz** [comment]
ideally we want to exit non-zero if something bad happens in the parsing.  for now I'm happy enough to find crashes.

btw: I looked at your patch and I can't accept it as is.  you need to write a real cmake loop, something like (not tested):

glob(TEST_FILES "*.ics")
foreach (TEST_FILE ${TEST_FILES})
  add_test(paser-${TEST_FILE} COMMAND parser ${TEST_FILE})
endforeach()
