### ISSUE TITLE
Change -DUSE_INTEROPERABLE_VTIMEZONES default

### ISSUE THREAD

**Issue by winterz** [libical/libical#256]
See the discussion at http://lists.infradead.org/pipermail/libical-devel/2016-January/000656.html

**Comment by ksuther** [comment]
One practical reason to switch this default: It fixes expanding time zones past 2038 (otherwise icaltime_convert_to_zone will fail).

We've been running with USE_INTEROPERABLE_VTIMEZONES off because we have a separate layer that makes compact interoperable VTIMEZONE rules and didn't need it, but this fixes behavior internal to libical as well.

**Comment by winterz** [comment]
just to be clear:  we will now use USE_INTEROPERABLE_VTIMEZONES=True by default.
any objections?

**Comment by winterz** [comment]
Done in ff70a4ca002148c33dec543697e0403e5691e883
