### ISSUE TITLE
API passbyvalue

### ISSUE THREAD

**Issue by winterz** [libical/libical#387]
Coverity is (rightly) complaining about some functions that take moderately sized structures where we it would be better to pass pointers to those structures.

in particular we pass struct icalrecurrencetype in quite a few places.
this would be an API change, unfortunately.   in 3.1 we should deprecate the bad signatures and remove those in 4.0

look for all functions where we pass structs and not pointers to structs and try to be consistent about it.

**Comment by minichma** [comment]
Copied over from duplicate #548:

The `icalrecurrencetype` struct is passed throughout libical by value. This probably has historic reasons, as it doesn't require much memory management and used to be sufficient. But with introduction of rscale, the new `icalrecurrencetype.rscale` attribte was introduced, which points at a dynamically allocated block of memory. The benefit of easy memory management is gone since then, as anyone using the type now needs to manage the referenced memory.

So this is to discuss, whether it would make sense to treat `icalrecurrencetype` as a reference type. This would mean introducing funcs like `icalrecur_new()`, `icalrecur_free()` and `icalrecur_clone()`. Cloning and freeing the rscale memory would be done inside `icalrecur_clone()` and `icalrecur_free()`, which would improve encapsulation and decoupling.

Another benefits would be, that the type could be made more dynamic as a whole over time. Today the size of the type is quite large, which can (and does) cause issues on resource-constrained devices, like embedded ones. By making it a reference type and centralizing the type's memory management within `icalrecur.c`, we could easily make it more dynamic. E.g. we could replace the big static by_xxx arrays with dynamic ones, therefore saving significant amounts of memory (in most cases).

The major downside would be backwards-compatibility. I.e. `icalproperty_new_rrule()` et al. would change their signature, as they would have to take pointers instead of values. Are these functions considered public? This would probably require introducing this only in a new major version, right?

We implemented something like this in a fork foccussed at embedded devices. The main changes (based on a version from 2018) can be seen here (including both, the change to a reference type as well as replacing the static by_xxx arrays):
https://github.com/tapkey/libical/compare/5683dd4..9579d55

If considered beneficial, I'd consider refurbishing the change and contributing it back to libical.

**Comment by minichma** [comment]
If we want to have both versions (byref and byval) at least between versions 3.1 and 4.0, we need to find new names for the new versions. Which names would be good ones?

`icalrecur_iterator_new ` -> `icalrecur_iterator_new_r`, `icalrecur_iterator_new_byref`, ...?
`icalrecurrencetype_from_string` -> ?
`icalvalue_xxx_recur` -> ?
`icalproperty_xxx_exrule` -> ?
`icalproperty_xxx_rrule` -> ?

Are we also talking about other types of values? What about these?
* `icaltimetype`
* `icaldurationtype`
* `icalperiodtype`
* `icaldatetimeperiodtype`
* `icaltriggertype`
* `icalreqstattype`
* `icalgeotype`

Would it be sufficient to start with icalrecurrencetype as this one seems to be the most relevant one (due to its size and complexity)?

**Comment by minichma** [comment]
@winterz If we want to handle `icalrecurrencetype` by ref, how would we manage memory in `icalvalue`? We have at least two options:

* Reference counting as done in case of `icalattach`: When dealing with instances of `icalattach`, `icalvalue` never clones such, neither when they are set nor when returned but uses reference counting instead. This option is more efficient at runtime but is somewhat more involved implementation-wise and also more complex to be used.
* Cloning instances when being set or retrieved as done in case of string values (text, uri, string) today: Each time a new value is set or the value is retrieved, the string is cloned. Somewhat more expensive at runtime but easy to use. But reference counting wouldn't be an option for these anyways, as there is no place to store the counter.

I feel that reference counting would be the way. Right?

**Comment by winterz** [comment]
> I feel that reference counting would be the way. Right?

agreed.  this would be great to have in 4.0 for sure

**Comment by minichma** [comment]
Yeah, I think this would be great, it's really one of the main challenges we have with using libical. I started working on it, but it's quite some work. Might need some help with polishing at the end, like updating docs, etc.
