### ISSUE TITLE
Ninja dupbuild=err cmake -G Ninja -DICAL_GLIB=ON -DSTATIC_ONLY=ON ..

### ISSUE THREAD

**Issue by winterz** [libical/libical#527]
happening in the 3.0 branch

mkdir build; cd build; cmake -G Ninja -DICAL_GLIB=ON -DSTATIC_ONLY=ON ..

fails with
```
CMake Error:
  Running

   '/usr/bin/ninja-build' '-C' '/home/allen/projects/libical/libical/build-foo' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:2134: multiple rules generate lib/libical-glib.a [-w dupbuild=err]
```

**Comment by kuruczgy** [comment]
`-DICAL_GLIB=ON` is the difference, both the reporter of #475 and I were testing with `-DICAL_GLIB=OFF`. Trying with `-DICAL_GLIB=OFF`, `master` works for me, so I am pretty sure this is the issue.

My PR #477 basically extended the `if(NOT SHARED_ONLY)` conditions to `if(NOT SHARED_ONLY AND NOT STATIC_ONLY)`.
If I do `git grep 'if(NOT SHARED_ONLY)'`, it finds `src/libical-glib/CMakeLists.txt`, further supporting that glib is the issue.

I think that I just forgot to change `src/libical-glib/CMakeLists.txt` in #477 (because I wasn't testing with it), and it seems pretty likely that doing the same changes there would fix this issue.

**Comment by wrobelda** [comment]
> I think that I just forgot to change `src/libical-glib/CMakeLists.txt` in #477 (because I wasn't testing with it), and it seems pretty likely that doing the same changes there would fix this issue.

Indeed, this fixed it. Thanks!

**Comment by wrobelda** [comment]
FYI, https://github.com/microsoft/vcpkg/pull/21667
