### ISSUE TITLE
RFCS.md

### ISSUE THREAD

**Issue by winterz** [libical/libical#566]
Rather than duplicating the RFCs we support in several places (README.md, Mainpage.dox, UsingLibical.md) can we have one RFCS.md that contains the authoritative list and we embed that into the other md and dox files

CC: @mcclurgm

**Comment by mcclurgm** [comment]
This makes sense. Although once we de-duplicate README.md and Mainpage.dox, I wonder if this is necessary? It only appears in two places. I'll defer to your judgment though.

It's also unclear to me how to embed a markdown file in another markdown file or if you can, but any way around it I'll copy my warning from the other issues you opened this morning. Once we start using Doxygen embeds and such, then the files will break in other renderers like GitHub and in this case lead to missing content. That would include the library homepage at github.io.

**Comment by winterz** [comment]
How about:

1. replace Mainpage.dox with README.md
2. in UsingLibical we can simply refer people to an anchor in README.md that has the supported RFCs list.

step1a is to munge the Mainpage.dox + README.md into 1 top-level documentation landing page
do you want to handle that?  or I can.

**Comment by winterz** [comment]
I'm not sure how to make an anchor in the README.md file. 
@mcclurgm can you take this one?

**Comment by mcclurgm** [comment]
Definitely! Sorry I lost track of this one. 

I can certainly make an anchor in README.md. However, that will require the same `{#header}` syntax that we just removed from from the h1 tag in #576. So your call whether you want to reintroduce that.

An alternative would be to add a simple link to the README.md _file_ from UsingLibical.md, instead of the RFCs section specifically. It would be a little less nice to read, but would maintain compatibility with GitHub.

I'll push a branch with the update so you can see how it looks on Doxygen and GitHub.
