### ISSUE TITLE
recurrence BYSETPOS is still not working in Subird  [sf#67]

### ISSUE THREAD

**Issue by winterz** [libical/libical#67]
from https://bugzilla.mozilla.org/show\_bug.cgi?id=322458

Klaus 2009-10-07 09:06:31 PDT 
Subird 1.9.1.3567: BYSETPOS is still not working :-\(

with todays \(2009-10-07\) nightlybuild "sunbird-1.0pre.en-US.win32.installer.exe" dated on
"October 7th 2009" BYSETPOS is still not working :-\(

my current workaround:

after exporting from msoutlook2007 

i have to do replacements in the ics file like 
replace "BYDAY=TH;BYSETPOS=2" with "BYDAY=2TH" 
replace "BYDAY=MO;BYSETPOS=-1" with "BYDAY=-1MO" 

after that the recurrences are fine with sunbird.

msoutlook2007 can interpret this format, too.
unfortunately msoutlook2007 converts them back to BYSETPOS :-\(

see also http://freeassociation.svn.sourceforge.net/viewvc/freeassociation/trunk/libical/src/libical/icalrecur.c?r1=926&r2=927&
and http://freeassociation.svn.sourceforge.net/viewvc/freeassociation/trunk/libical/src/libical/icalrecur.c?r1=961&r2=962&

**Comment by ksmurchison** [comment]
This appears to be fixed in master:

RRULE:FREQ=MONTHLY;COUNT=12;BYDAY=TH;BYSETPOS=2
DTSTART:20150108
INSTANCES:20150108,20150212,20150312,20150409,20150514,20150611,20150709,20150813,20150910,20151008,20151112,20151210

RRULE:FREQ=MONTHLY;COUNT=12;BYDAY=MO;BYSETPOS=-1
DTSTART:20150126
INSTANCES:20150126,20150223,20150330,20150427,20150525,20150629,20150727,20150831,20150928,20151026,20151130,20151228

**Comment by winterz** [comment]
closing
