### ISSUE TITLE
Error on macOS 14: `libical-glib-private.h:119:2: error: #endif without #if`

### ISSUE THREAD

**Issue by barracuda156** [libical/libical#723]
Got a weird error on macOS 14 CI:

```
  In file included from /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_libical/libical/work/build/src/libical-glib/i-cal-attach.c:24:
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_libical/libical/work/build/src/libical-glib/libical-glib-private.h:119:2: error: #endif without #if
  #endif
   ^
  1 error generated.
  make[2]: *** [src/libical-glib/CMakeFiles/ical-glib.dir/i-cal-attach.c.o] Error 1
  make[2]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_libical/libical/work/build'
  make[1]: *** [src/libical-glib/CMakeFiles/ical-glib.dir/all] Error 2
```

Log: https://github.com/macports/macports-ports/actions/runs/10446373347/job/28923692179?pr=25391

**Comment by winterz** [comment]
I don't know what could be wrong but it does bring up the point that we need to support more platforms in our .github/workflows /build.yml

if anyone knows how, would be nice to add macos-13 and macsos-14.  and any other useful platforms

**Comment by barracuda156** [comment]
MacPorts has CI on those, perhaps the setup can be just copied? And many repos do. Current MacOS on mainstream archs aren’t really exotic.

**Comment by mcrha** [comment]
I sometimes get this error, a simple rebuild usually helps (usually one, but...).

I believe the dependencies of the custom commands are set properly, but it seems they are not. I think the problem is that the build runs several parts of the library in parallel and for some reason also the libical-glib's API files transform from .xml to .c/.h files sometimes happens at the same time, effectively overwriting the `build/src/libical-glib/libical-glib-private.h` in the middle of the write from another thread/process/whatever CMake calls it when it runs the build in parallel. it's a timing issue, because the other time it is fine.

I do not know how to fix this properly. Thinking of it now, maybe the custom command to create those files may create some file not directly, but through a temporary file and rename that temporary file only after the content of it is fully populated. But whether it's it, I do not know.

You should be able to workaround the problem by running `make -j1` or `ninja -j1` or a similar option in the build command you configure the project with. Make sure you clean up the build directory before it, at least the generated libical-glib files.

**Comment by barracuda156** [comment]
OK, CI pass without parallel build, closing. Not a perfect solution, but we can live with it.

**Comment by winterz** [comment]
I just hit this on my linux system.  looks like libical-glib-private.h is getting messed up .  I'll look into it
